### ISSUE TITLE
write of correct seedlink config for station with 2 dataloggers no longer works

### ISSUE THREAD

**Issue by grapagnani** [SeisComP/seedlink#16] opened 2024-10-23 09:27 UTC
Hello,
I have a station BE.MEM for which I was able to **simultaneously** get seedlink streams from 2 dataloggers when using SC3 2017.334.05.
I am now running SeisComP 6.5.0 on Ubuntu 24.04 and it no longer works.

This is my seedlink key file (that I validated using seiscomp exec scconfig on SC 6.5.0):
```
# Activated plugins for category sources
sources = chain0:chain,chain1:chain

# Hostname or IP of the Seedlink server.
sources.chain0.address = host55.example.com

# Port of the Seedlink server
sources.chain0.port = 18000

# List of stream selectors. If left empty all available streams will be
# requested. See slinktool manpage for more information.
sources.chain0.selectors = BDI

# Defines the input network if different from the stations
# network. Usually leave this parameter unconfigured. If
# configured and different from the stations network code
# the network code will be renamed to match the local network
# code.
sources.chain0.network = SG

# Defines the input station if different from the stations
# code. Usually leave this parameter unconfigured. If
# configured and different from the stations code
# the station code will be renamed to match the local station
# code.
sources.chain0.station = MEMB

# Hostname or IP of the Seedlink server.
sources.chain1.address = host55.example.com

# Port of the Seedlink server
sources.chain1.port = 10800

# List of stream selectors. If left empty all available streams will be
# requested. See slinktool manpage for more information.
sources.chain1.selectors = !EX?,!GEL,!GLA,!GLO
```
After 1 hour from starting seedlink, the BDI stream is still not retrieved by seedlink.

In the seedlink.log file, I see the message:
`chain0: /home/seedlink/seiscomp/var/lib/seedlink/chain0.xml:70: station ID BE.MEM is already in use`

Indeed, in the chain0.xml, I notice twice the BE.MEM id:
```
...
  <group address="host55.example.com:10800"
         seqfile="/home/seedlink/seiscomp/var/run/seedlink/membach.oma.be:10800.seq"
         lockfile="/home/seedlink/seiscomp/var/run/seedlink/membach.oma.be:10800.pid"
         batchmode="yes">
    <station id="BE.MEM" name="MEM" network="BE" selectors="!EX? !GEL !GLA !GLO"/>
  </group>
  <group address="host55.example.com:18000"
         seqfile="/home/seedlink/seiscomp/var/run/seedlink/membach.oma.be:18000.seq"
         lockfile="/home/seedlink/seiscomp/var/run/seedlink/membach.oma.be:18000.pid"
         batchmode="yes">
    <station id="BE.MEM" name="MEMB" out_name="MEM" network="SG" out_network="BE" selectors="BDI"/>
    <station id="BE.MEMS" name="MEMS" network="BE" selectors=""/>
  </group>
...
```
With SC3 2017.334.05, the two groups above were split respectively into chain1.xml and chain0.xml files. And the seedlink.ini would cause spawning 2 chain plugins thanks this configuration:
```
* template: /home/seedlink/seiscomp/share/templates/seedlink/chain/seedlink_plugin.tpl
plugin chain0 cmd="/home/seedlink/seiscomp/share/plugins/seedlink/chain_plugin -v -f /home/seedlink/seiscomp/var/lib/seedlink/chain0.xml"
             timeout = 600
             start_retry = 60
             shutdown_wait = 15
* template: /home/seedlink/seiscomp/share/templates/seedlink/chain/seedlink_plugin.tpl
plugin chain1 cmd="/home/seedlink/seiscomp/share/plugins/seedlink/chain_plugin -v -f /home/seedlink/seiscomp/var/lib/seedlink/chain1.xml"
             timeout = 600
             start_retry = 60
             shutdown_wait = 15
```

On SC 6.5.0, I manually adapted chain0.xml, seedlink.ini files and created chain1.xml, mimicing the config on SC3 2017.334.05, and now seedlink does retrieve the seedlink streams from both datalogger simultaneously.

I had a look in the forum and the closed issues, as well the changelog in 6.5.1, I was not able to find any info about a similar issue.
Is this a known issue ?

**Comment by gempa-jabe** [comment] 2024-10-23 09:30
I think in your case it uses `sources.chain0.station` as key and does not split the instances because `MEM` and `MEMB` are different. Could you try to replace `sta` with `seedlink.sta` in https://github.com/SeisComP/seedlink/blob/master/templates/chain/setup.py#L193?

**Comment by luca-s** [comment] 2024-10-23 09:35
It looks like [this](https://github.com/SeisComP/seedlink/commit/8d1076922a8f61a0af8a99962ebcba6a2d7bf7cb) commit is the culprit.

The goal of that commit was to split the data from the same datalogger to 2 separate stations. Your goal, instead, is to join 2 dataloggers in one station. I didn't consider that scenario when I created the PR.

**Comment by gempa-jabe** [comment] 2024-10-23 09:51
So we could use as index a combination of both:

```python
station_key = seedlink.net + "." + seedlink.sta + "." + sta
```

That should split in both cases.

**Comment by grapagnani** [comment] 2024-10-23 10:28
Setting the key like this: `station_key = seedlink.net + "." + seedlink.sta + "." + sta`
still doesn't split.

Reverting the commit 8d10769 does produce the split.

**Comment by grapagnani** [comment] 2024-10-23 12:30
I created a single seiscomp configuration using the key files found in the issue https://github.com/SeisComP/seedlink/issues/8 and the key files for my problematic station BE.MEM.
The patch below makes setup.py manages the configuration correctly, creating 2 chains and splitting the stations from each of the 2 use cases in different chains.

```
--- seiscomp/share/templates/seedlink/chain/setup.py.orig	2024-10-23 10:16:42.585903998 +0000
+++ seiscomp/share/templates/seedlink/chain/setup.py	2024-10-23 12:19:57.219152555 +0000
@@ -187,14 +187,24 @@ class SeedlinkPluginHandler:
 
     # Find out what chain.xml instance to use
     try:
-        sta = seedlink.param("sources.chain.station")
-    except: sta = seedlink.sta
+        in_net = seedlink.param("sources.chain.network")
+    except: in_net = seedlink.net
 
-    station_key = seedlink.net + "." + sta
+    try:
+        in_sta = seedlink.param("sources.chain.station")
+    except: in_sta = seedlink.sta
+
+    station_key = seedlink.net + "." + seedlink.sta + "." + in_net + "." + in_sta
 
     chain_instance = 0
-    if station_key in self.stations:
-      chain_instance = self.stations[station_key]+1
+
+    for sta in self.stations.keys():
+        # comparison against locally configured net.sta
+        if '.'.join(station_key.split('.')[0:2]) == '.'.join(sta.split('.')[0:2]):
+            chain_instance += 1
+        # comparison against net.sta configured at the source server/instrument
+        elif '.'.join(station_key.split('.')[2:]) == '.'.join(sta.split('.')[2:]):
+            chain_instance += 1
 
     self.stations[station_key] = chain_instance
```

**Comment by grapagnani** [comment] 2024-10-23 12:43
a cleaner version:
```
--- seiscomp/share/templates/seedlink/chain/setup.py.orig	2024-10-23 10:16:42.585903998 +0000
+++ seiscomp/share/templates/seedlink/chain/setup.py	2024-10-23 12:39:24.301413932 +0000
@@ -187,14 +187,24 @@ class SeedlinkPluginHandler:
 
     # Find out what chain.xml instance to use
     try:
-        sta = seedlink.param("sources.chain.station")
-    except: sta = seedlink.sta
+        in_net = seedlink.param("sources.chain.network")
+    except: in_net = seedlink.net
 
-    station_key = seedlink.net + "." + sta
+    try:
+        in_sta = seedlink.param("sources.chain.station")
+    except: in_sta = seedlink.sta
+
+    station_key = seedlink.net + "." + seedlink.sta + "_" + in_net + "." + in_sta
 
     chain_instance = 0
-    if station_key in self.stations:
-      chain_instance = self.stations[station_key]+1
+
+    for sta in self.stations.keys():
+        # comparison against locally configured net.sta
+        if station_key.split('_')[0] == sta.split('_')[0]:
+            chain_instance += 1
+        # comparison against net.sta configured at the source server/instrument
+        elif station_key.split('_')[1] == sta.split('_')[1]:
+            chain_instance += 1
 
     self.stations[station_key] = chain_instance
```

**Comment by gempa-jabe** [comment] 2024-10-23 13:02
My proposal does not work because "BE.MEM.MEMB" is not "BE.MEM.MEM". The input station code differs, my bad.

@luca-s can you provide an example configuration that should work for you and an expected result? As I can reproduce @grapagnani's issue, it would be good to have your reference as well to validate possible fixes.

**Comment by gempa-jabe** [comment] 2024-10-23 13:06
I found them in #8, thanks @grapagnani. Being able to read properly gains a lot of advantage ... ;)

**Comment by gempa-jabe** [comment] 2024-10-23 13:32
> a cleaner version:
> 
> ```
> --- seiscomp/share/templates/seedlink/chain/setup.py.orig	2024-10-23 10:16:42.585903998 +0000
> +++ seiscomp/share/templates/seedlink/chain/setup.py	2024-10-23 12:39:24.301413932 +0000
> @@ -187,14 +187,24 @@ class SeedlinkPluginHandler:
>  
>      # Find out what chain.xml instance to use
>      try:
> -        sta = seedlink.param("sources.chain.station")
> -    except: sta = seedlink.sta
> +        in_net = seedlink.param("sources.chain.network")
> +    except: in_net = seedlink.net
>  
> -    station_key = seedlink.net + "." + sta
> +    try:
> +        in_sta = seedlink.param("sources.chain.station")
> +    except: in_sta = seedlink.sta
> +
> +    station_key = seedlink.net + "." + seedlink.sta + "_" + in_net + "." + in_sta
>  
>      chain_instance = 0
> -    if station_key in self.stations:
> -      chain_instance = self.stations[station_key]+1
> +
> +    for sta in self.stations.keys():
> +        # comparison against locally configured net.sta
> +        if station_key.split('_')[0] == sta.split('_')[0]:
> +            chain_instance += 1
> +        # comparison against net.sta configured at the source server/instrument
> +        elif station_key.split('_')[1] == sta.split('_')[1]:
> +            chain_instance += 1
>  
>      self.stations[station_key] = chain_instance
> ```

I am not sure what happens if a third station comes into play using the same input station. I think it would also split on 1 rather than 2 and we would end up with "already defined" error.

Actually what I think to have learned:

* chain_plugin does not allow the same station id within one XML file, within the same group or not does not matter
* chain_plugin does not allow duplicates of `${in_network}.${in_station}` within one XML file, within the same group or not does not matter

So we need to keep track of the instances of a particular station id and furthermore of the input station descriptor independently. The final instance number would be the sum of both. I haven't though about all corner cases right now.

@andres-h

**Comment by andres-h** [comment] 2024-10-23 13:52
I'll try to remove some of those restrictions from chain_plugin. Since one group corresponds to one seedlink connection, having duplicate `${in_network}.${in_station}` within one group would not be possible, but other restrictions might not be needed technically.

**Comment by gempa-jabe** [comment] 2024-10-23 14:12
Maybe because of sequence number files which could create conflicts ...

**Comment by andres-h** [comment] 2024-10-23 18:09
There should be no conflicts when `${in_network}.${in_station}` is unique within group. I just created an experimental patch at https://github.com/SeisComP/seedlink/pull/17

**Comment by grapagnani** [comment] 2024-10-24 08:27
> 
> I am not sure what happens if a third station comes into play using the same input station. I think it would also split on 1 rather than 2 and we would end up with "already defined" error.
> 
> Actually what I think to have learned:
> 
>     * chain_plugin does not allow the same station id within one XML file, within the same group or not does not matter
> 
>     * chain_plugin does not allow duplicates of `${in_network}.${in_station}` within one XML file, within the same group or not does not matter
> 
> 
> So we need to keep track of the instances of a particular station id and furthermore of the input station descriptor independently. The final instance number would be the sum of both. I haven't though about all corner cases right now.
> 
> @andres-h

I have tested the patch against a single seiscomp config where both use cases are configured simultaneously:
- A) 10 stations are created from 1 remote station. I configured various channel selectors and renames (with/without location code);
- B) 1 station is created from 10 remote stations. I configured various channel selectors and renames (with/without location code);

In use case B, one of the 10 remote stations is the same remote station used in use case A.
The seedlink configuration is created correctly with 11 chains.
When starting seedlink, all the 11 stations appears with streams retrieved and renamed as instructed in the key files.
The sequence files have different names.

The key files and the corresponding produced seedlink configuration is here: [config.tar.gz](https://github.com/user-attachments/files/17503818/config.tar.gz)

**Comment by gempa-jabe** [comment] 2024-10-24 08:31
Thank you for the testing. That seems to be a great outcome. That means we do not need to patch the `setup.py` but only `chain_plugin`? How do the sequence file names look like? Usually it was `$host:$port.seq`. Has that changed now?

**Comment by grapagnani** [comment] 2024-10-24 08:35
I have not tested the patch of Andres. I have tested my patch of `setup.py`.

**Comment by gempa-jabe** [comment] 2024-10-24 08:46
Ah, OK. Given your test files, as all chains connect to `slserver.example.com:18000` and, e.g. stations XX.STA01 and ZZ.STA01 receive from BE.SBOT, which sequence number will eventually be written into `slserver.example.com:18000.seq`? This is probably more of a `chain_plugin` question and not really connected to this issue. In my understanding this could lead to data gaps after a restart. While we are on this topic, it would make sense to tackle such possible issues as well.

**Comment by grapagnani** [comment] 2024-10-24 09:04
Further below the content of the seq files. I don't know exactly what I need to check.
Would it be a conclusive test if I enable slarchive, do `seiscomp stop; sleep 10; seiscomp start` every 10 min during a couple of hours and finally verify for any gaps inside the archive of miniseed files ?
Note that I'd be happy to test the patch of Andres with an unmodified setup.py if you provide me the required binaries for Ubuntu 24.04.
```
slserver.example.com:18000.10.seq:BE SBOT 16491247 2024,10,24,08,57,22
slserver.example.com:18000.1.seq:BE A064 13437938 2024,10,24,08,57,56
slserver.example.com:18000.1.seq:BE SBOT 16491298 2024,10,24,08,57,57
slserver.example.com:18000.2.seq:BE A052 1611128 2024,10,24,08,57,57
slserver.example.com:18000.2.seq:BE SBOT 16491299 2024,10,24,08,57,58
slserver.example.com:18000.3.seq:BE A053 10640154 2024,10,24,08,57,55
slserver.example.com:18000.3.seq:BE SBOT 16491297 2024,10,24,08,57,57
slserver.example.com:18000.4.seq:BE A054 10559965 2024,10,24,08,57,59
slserver.example.com:18000.4.seq:BE SBOT 16491303 2024,10,24,08,58,01
slserver.example.com:18000.5.seq:BE A055 7927919 2024,10,24,08,58,00
slserver.example.com:18000.5.seq:BE SBOT 16491304 2024,10,24,08,58,02
slserver.example.com:18000.6.seq:BE A056 9185179 2024,10,24,08,57,53
slserver.example.com:18000.6.seq:BE SBOT 16491297 2024,10,24,08,57,57
slserver.example.com:18000.7.seq:BE A057 10122726 2024,10,24,08,57,54
slserver.example.com:18000.7.seq:BE SBOT 16491298 2024,10,24,08,57,57
slserver.example.com:18000.8.seq:BE A058 4039685 2024,10,24,08,57,53
slserver.example.com:18000.8.seq:BE SBOT 16491293 2024,10,24,08,57,54
slserver.example.com:18000.9.seq:BE SBOT 16491264 2024,10,24,08,57,34
slserver.example.com:18000.seq:BE A050 11023866 2024,10,24,08,57,57
slserver.example.com:18000.seq:BE SBOT 16491300 2024,10,24,08,57,59
```

**Comment by gempa-jabe** [comment] 2024-10-24 09:12
The chain instance is part of the sequence file name so everything should be fine. It was my doubt due to missing knowledge, now it is clear to me. The sequence file issue is not an issue anymore ;)

**Comment by andres-h** [comment] 2024-10-24 13:20
> Note that I'd be happy to test the patch of Andres with an unmodified setup.py if you provide me the required binaries for Ubuntu 24.04.

I hope setup.py modification is not needed, because the chain_plugin change should resolve the issue. I attach the chain_plugin binary for Ubuntu 24.04.

[chain_plugin.gz](https://github.com/user-attachments/files/17507362/chain_plugin.gz)

**Comment by grapagnani** [comment] 2024-10-25 11:46
Thanks for the updated binary .

I have restored the `setup.py` file to its original state, installed your `chain_plugin` file and cleaned the directories `var/lib/seedlink/buffer/` and `var/run/seedlink/`. Then I started seedlink.

There are  streams ( `ZZ.STA01.02.LP?` ) that are not retrieved because the source station (`BE.SBOT`) is already defined in the `chain0.xml` for the station `XX.STA01` . This is the message inside `seedlink.log`:
`/home/gio/seiscomp/var/lib/seedlink/chain0.xml:54: station BE.SBOT is already used in group`

I doubled checked that the binary was correctly installed:
`sha1:bf80b4eb738262544882923de112e7606fd8a93e  /home/gio/seiscomp/share/plugins/seedlink/chain_plugin`

I give you in attachment all the seedlink key files and the corresponding seedlink configuration written by `seiscomp update-config`, and the seedlink.log:  [config_and_log.tar.gz](https://github.com/user-attachments/files/17521519/config_and_log.tar.gz)

**Comment by grapagnani** [comment] 2024-10-25 12:14
We need to split based on the remote net.sta.
This small patch to `setup.py` solves the issue:
```
--- seiscomp/share/templates/seedlink/chain/setup.py.orig	2024-07-17 12:29:26.000000000 +0000
+++ seiscomp/share/templates/seedlink/chain/setup.py	2024-10-25 12:09:15.528818533 +0000
@@ -187,10 +187,13 @@ class SeedlinkPluginHandler:
 
     # Find out what chain.xml instance to use
     try:
+        net = seedlink.param("sources.chain.network")
+    except: net = seedlink.net
+    try:
         sta = seedlink.param("sources.chain.station")
     except: sta = seedlink.sta
 
-    station_key = seedlink.net + "." + sta
+    station_key = net + "." + sta
 
     chain_instance = 0
     if station_key in self.stations:
```

**Comment by andres-h** [comment] 2024-10-25 13:40
> There are streams ( `ZZ.STA01.02.LP?` ) that are not retrieved because the source station (`BE.SBOT`) is already defined in the `chain0.xml` for the station `XX.STA01` . This is the message inside `seedlink.log:
/home/gio/seiscomp/var/lib/seedlink/chain0.xml:54: station BE.SBOT is already used in group`

That's the limitation I mentioned. It is not possible to request a station twice using a single seedlink connection. I was hoping that setup.py already takes care of that, but looks like the patch above solves the problem. I'll add it to the pull request.

**Comment by grapagnani** [comment] 2024-10-26 07:13
Thanks for the fix.

**Comment by andres-h** [comment] 2024-10-28 15:11
I've merged the pull request. If you notice problems, let me know.

**Closed as completed by andres-h** 2024-10-28 15:11 UTC
